source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UserInitialsIcon_Example', :exclusive => true do
  pod "UserInitialsIcon", :path => "../"
end

target 'UserInitialsIcon_Tests', :exclusive => true do
  pod "UserInitialsIcon", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
